language: python
python:
  - 3.5
  - 3.6
git:
  submodules: false
install:
  - pip install -r requirements.txt
env:
  global:
    - SECRETS_DIR: "secrets"
    - IRC_PASSWORD: "foobar"
    - secure: "K2roBd8snP+C4VQMYbA0t40aamVrSTQ7j2lt+jv9icEzPlgSGMexU3iNbVmNeiDvEMKZKzoo9zEF3ADur4/9cI6rmqqZ4xPq2MJImEVHJ8stoGvU9tTzSI7KcsF617oIPUZf+PL7RnETOROU4/qfbuB37cQM6mZXlmc9brmPaHvZ38kInbT3Z+5SASAPDn9Iu4zxJ38dMg1eO3BV8DdjlickdXKbbWt72yXDfPJFaLOsiWs24dW9mINXVDeui1NZtAbC6NWEXNdPkTQviPjaer3dVdQy/bXGvf4bQ4aH8EEd9oX62i0IiGm1n4KoutLza/pEAirqGDvM5KU2u4hlCroJgKE3c1NDmykFqANajU+5T/6tQJ1yYhtUAt+j60uG16u4tNHMYf+JCkIgwJsgwwjVVNVu5M6IXHVFih85d9bXanD3STLLMWd3gtK1t8osDz5NlVeD/K7JU6Kg6Le1mb3E7B5tFw6EKWKhpsWuo5ALIX9ly9TBcpYvkShUXLK/ecYRlwM615phlBxv0lz2tENe3CHww+eGkLhcgR6QUE/soxaNP07srP8IOUrQQv2ICkjzgCa+hdo7lPbCKt2yJ0JfZH+Z/KHTuVFdiC+sjSKfrPP659Ti1ppYJFWOLu2dR+pynYw54pUiFApFYP2ITTM7ZYDo637PY5uDM87iGSc="
      
jobs:
  include:
    - stage: deploy-docs
      python: 3.6
      script:
        - cd docs
        - make html
        - cd ..
        - doctr deploy .
script:
  - ./travis-checkconfig.py
  - buildbot checkconfig
